### ISSUE TITLE
Migrate Schema Registry to a standalone repo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1767]
Notes:
- [x] Decide the name for the repo
- [x] Setup CI plans
- [x] Decouple Schema Registry dependency from SCSt's message converter
- [x] Decide where to host the docs
- [x] Adjust SCSt samples 
- [x] Disconnect StreamMessageConverter
- [x] Remove schema registry code from core Spring Cloud Stream

**Comment by jmax01** [comment]
While this is likely a bridge too far for 3.0, long term it would be ideal if core `Avro` support was extracted and placed in other libraries and repos. 

Ideally _spring-avro_ would be a project under _spring-projects_ containing the following: 

- shared serialization/deserialization logic (_spring-avro-core_)
   Currently in _spring-framework_, since there is no _spring-jackson-core_ module, there is more than a
    trivial amount of duplication when it comes to _Jackson_ _JSON_ processing.   
- _spring-messaging_ support (_spring-avro-messaging_) 
-  _spring-web*_ support (_spring-avro-web*_)

If dedicated _spring-integration_ support is required a _spring-integration-avro_ module/project should be created.


As far as I can tell direct dependence on _spring-integration_, _spring-boot_, and _spring-cloud_ is limited to configuration (easily addressed) and the use of [BinderHeaders](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/BinderHeaders.java) in [OriginalContentTypeResolver](/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/OriginalContentTypeResolver.java) and this usage is limited to accessing the [BinderHeader's BINDER_ORIGINAL_CONTENT_TYPE ](https://github.com/spring-cloud/spring-cloud-stream/blob/28894afed7dd02c7fc0a9969f378f6901f5eb048/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/BinderHeaders.java#L35) key constant.

Is `BINDER_ORIGINAL_CONTENT_TYPE` even a thing in 3.0?  If not I don't really see a technical barrier to moving the most _Avro_ support  to dedicated projects/modules.

Having _Avro_ support out of the _integration/boot/cloud_ dependency hierarchy would have been very helpful for us as we have a mixed environment of both _boot_ and _non-boot_ apps.

**Comment by sobychacko** [comment]
@jmax01 - Thank you for the analysis. As a first step, we are thinking to move the current schema registry code from core Spring Cloud Stream into its own repository. As we iterate through this effort, we can potentially isolate the avro converters into a higher level repository. 

The original content type will be removed from the 3.0. I think its already deprecated.

**Comment by jmax01** [comment]
@sobychacko  I totally understand.  

However since I discovered that minimal _Avro_ support has recently been added to _spring-integration_ there are now two _Spring_ implementations for dealing with _Avro_ and this makes me of the opinion that a _spring-avro_ project should be pursued sooner rather than later. 

BTW @garyrussell created [this](https://github.com/spring-projects/spring-integration/issues/2992)  to track creating possibly adding a _spring-integration-avro_ module.

**Comment by artembilan** [comment]
Looks like this is done: https://github.com/spring-cloud/spring-cloud-schema-registry

**Comment by olegz** [comment]
Resolved
