### ISSUE TITLE
Miscellaneous tasks before 3.0

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1805]
Documentation:
- [ ] - Update "what's new" section
- [x] - Move/Remove schema evolution section 
- [x] - Remove StreamMessageConverter from the doc
- [x] - Deprecate reactive module
- [x] - Deprecate old test binder
- [x] - Revisit configuration property and auto-complete. We have some issue due to hierarchy. (see: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/739)
- [x] - Document @BindingProvider - removed
- [x] - Document PollableSupplier and `splittable` property
- [x] - Metrics Emitter???
- [x] - Note that `EnableBinding` and Functional are mutually exclusive, You can't have `EnableBinding` and Functions, since you may also have `StreamListener` and that may create a conflict
- [x] - document Source semantics for Supplier, polling mechanism etc
- [x] - document Spring Integration support with functions (see `IntegrationFlows.from(Function.class)`): https://docs.spring.io/spring-integration/docs/5.2.0.RELEASE/reference/html/dsl.html#java-dsl-gateway

Other:
- [x] - Error handling with function (strategy, tests, docs)
- [x] - Review all reactive code with reactive team specifically for error handling
- [x] - Move message converters into SCF
- [x] - Add additional tests for custom message converter given that `StreamMessageConverter` is deprecated
- [x] - remove original-content-type
- [ ] https://github.com/spring-cloud/spring-cloud-stream-starters/issues/102
