### ISSUE TITLE
Provide comprehensive tests for `contentType` conversion

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#992]
As a developer, I'd like to add test coverage for all the support content-type combinations.

**Tasks:**
- [ ] Source: `POJO` and Target: `JSON String`
- [ ] Source: `Tuple` and Target: `JSON String`
- [ ] Source: `POJO` and Target: `String (toString())`
- [ ] Source: `POJO` and Target: `byte[] (java.io serialized)`
- [ ] Source: `JSON byte[] or String` and Target: `JSON`
- [ ] Source: `byte[] or String` and Target: `Serializable`
- [ ] Source: `JSON byte[] or String` and Target: `Tuple`
- [ ] Source: `byte[]` and Target: `String`
- [ ] Source: `String` and Target: `byte[]`

**Comment by garyrussell** [comment]
@mbogoevici This is probably hijacking this issue, but I don't see one for the `null` payload conversion problem.

I wonder if fixing that issue might be as simple as...

```java
if (this.provideHint) {
	converted = ((AbstractMessageConverter) this.messageConverter).fromMessage(message, this.klazz,
			this.mimeType);
	if (converted == null) {
		// remove content type header and try again
		// add a warn log indicating the header needs to be remove
	}
	if (converted == null) // throw exception
}
```

**Comment by mbogoevici** [comment]
@garyrussell Definitely a welcome suggestion, but it might be a separate issue - what I wanted to capture here before I completely forgot is that we don't have a reference test for the http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR2/reference/htmlsingle/#mime-types-and-java-types

(The tests should capture the issues around null conversion).
